#!/bin/bash
# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

rename -v 's/([a-z])([A-Z0-9])/$1_$2/g' "$@"
rename -v 's/ /_/g' "$@"
rename -v 's/^([01][0-9][01][0-9][0-3][0-9][-.])/20$1/' "$@"
rename -v 's/^(9[0-9][01][0-9][0-3][0-9][-.])/19$1/' "$@"
