#!/bin/bash
# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

rename -v 's/Ä/Ae/g;s/Ö/Oe/g;s/Ü/Ue/g;s/ä/ae/g;s/ö/oe/g;s/ü/ue/g;s/\.([A-Z]{3})$/.\L$1/;s/([a-z])([A-Z0-9])/$1_$2/g;s/ /_/g;s/^([01][0-9][01][0-9][0-3][0-9][-.])/20$1/;s/^(9[0-9][01][0-9][0-3][0-9][-.])/19$1/' "$@"
